<a href="https://colab.research.google.com/github/shaillenkumar/Java8Concepts/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

import numpy as np

In [ ]:
a = np.array([1,2,3])

type(a)

numpy.ndarray

In [ ]:
b = np.array([['2',4,5,7,8],[1,2,3,4,5],[9,7,5,4,2]]) # the elements are homogenous types. you can see all elements converted to String.

print(b)

c = np.array([[2,4,5,7,8],[1,2,3,4,5],['9',7,5,4,2]],dtype=float) # dtype=float - we are instructing all the elements are type Float.

print(c)

# d = np.array([[2,4,5,7,8],[1,2,3,4,5],['shail',7,5,4,2]],dtype=float) # dtype=float - we are instructing all the elements are type Float -> this will give Error.



[['2' '4' '5' '7' '8']
 ['1' '2' '3' '4' '5']
 ['9' '7' '5' '4' '2']]
[[2. 4. 5. 7. 8.]
 [1. 2. 3. 4. 5.]
 [9. 7. 5. 4. 2.]]


In [ ]:
f = np.arange(1,50,4) # create array with a sequence of numbers starting from 1 to 50 incr by 4
print(f)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [ ]:
g = np.zeros((3,6))
print(g)
h = np.ones((3,6))
print(h)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
np.linspace(0,10,5) # you need numbers from 0 to 10 divide into 5 equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.random.randint(1,10,size=(2,3)) #provide the shape

array([[4, 4, 1],
       [7, 2, 2]])

In [ ]:
np.random.rand(3,2)

array([[0.28588986, 0.1095225 ],
       [0.31594397, 0.71941794],
       [0.29251156, 0.00906562]])

In [ ]:
a = np.array([4,9,8,2,5,1,0,7,11])
print(a[0:3])

print(a[:3])

print(a[3:])

print(a[a >7])    # boolean indexing only number greater than 7

print(a.shape)

[4 9 8]
[4 9 8]
[ 2  5  1  0  7 11]
[ 9  8 11]
(9,)


In [ ]:
b = np.array([[3,2,1],[7,6,5],[9,8,7]])

print(b.shape)
print("-----")
print(b[0:3])
print("-----")
print(b[2:])
print("-----")
print(b[0:3,0:2])
print("-----")
print(b[:,0:2])
print("-----")
print(b[:,0])
print("-----")
print(b[:,2])
print("-----")

(3, 3)
-----
[[3 2 1]
 [7 6 5]
 [9 8 7]]
-----
[[9 8 7]]
-----
[[3 2]
 [7 6]
 [9 8]]
-----
[[3 2]
 [7 6]
 [9 8]]
-----
[3 7 9]
-----
[1 5 7]
-----


In [ ]:
a = np.array([[3,2,1],[3,1,2],[0,5,4]])
b = np.array([[4,1,2],[2,1,3],[1,2,3]])
print(a+b)
print("-----")
print(a-b)
print("-----")
print(a*b)
print("-----")
print(10*a)
print("-----")
print(a.dot(b))
print("-----")
print(np.dot(a,b))
print("-----")


[[7 3 3]
 [5 2 5]
 [1 7 7]]
-----
[[-1  1 -1]
 [ 1  0 -1]
 [-1  3  1]]
-----
[[12  2  2]
 [ 6  1  6]
 [ 0 10 12]]
-----
[[30 20 10]
 [30 10 20]
 [ 0 50 40]]
-----
[[17  7 15]
 [16  8 15]
 [14 13 27]]
-----
[[17  7 15]
 [16  8 15]
 [14 13 27]]
-----


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([5,6,7]) # you will observer stretching of this array as [[5,6,7],[5,6,7]]

print(a+b)

array([[ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
a = np.array([[3,2,1],[3,1,2],[0,5,4]])

print(a.sum())
print("-----")

print(a.sum(axis = 0)) # along which direction we want to apply the aggrgate fucntion -  columns
print("-----")

print(a.sum(axis = 1)) # along which direction we want to apply the aggrgate fucntion -  rows

print("----")

print(a.max(axis=0))

print("----")

print(a.max(axis=1))

print("----")

print(a.mean(axis=1))
print("----")



21
-----
[6 8 7]
-----
[6 6 9]
----
[3 5 4]
----
[3 3 5]
----
[2. 2. 3.]
----


In [ ]:
c = np.arange(6)  #create a 1 -D array
print(c)

#shape manipulation
d =c.reshape(2,3)
print(d)

#shape manipulation - 4 D array
arr.reshape(2,1,1,3) # 2*3 =6, no of items: 6



[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


array([[[[0, 1, 2]]],


       [[[3, 4, 5]]]])

In [ ]:
# Copy vs View

a = np.array([5,3,2,8])

b = a.view()

c = a.copy()


b[2] = 100
print(b)
print(a) # changed a

a = np.array([5,3,2,8])

c[2] = 100
print(c)
print(a) # a unchanged





[  5   3 100   8]
[  5   3 100   8]
[  5   3 100   8]
[5 3 2 8]


In [ ]:
arr = np.array([5,3,2,8])

np.sort(arr)

array([2, 3, 5, 8])

In [ ]:
import time

lst = list(range(1_000_000)) #list
start = time.time()
[x*x for x in lst] #squaring all the items of the list

print("Python loop:", time.time()-start)

arr = np.arange(1_000_000) #numpy array
start = time.time()
arr**2 #element wise operation
print("NumPy:", time.time()-start)

Python loop: 0.15172219276428223
NumPy: 0.011208772659301758
